// <auto-generated />
using System;
using KJ.Portfolio.WebUI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KJ.Portfolio.WebUI.Migrations
{
    [DbContext(typeof(PortfolioDbContext))]
    [Migration("20260317122627_DatabaseDeneme1")]
    partial class DatabaseDeneme1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KJ.Portfolio.Web.Ui.Models.Entities.HomePage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AboutAwardDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AboutAwardIconClass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AboutAwardTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AboutButtonTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AboutButtonUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short?>("AboutClientCount")
                        .HasColumnType("smallint");

                    b.Property<string>("AboutClientTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AboutContentDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AboutContentTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AboutDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte?>("AboutExperienceListCount")
                        .HasColumnType("tinyint");

                    b.Property<string>("AboutExperienceListTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AboutImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short?>("AboutProjectCount")
                        .HasColumnType("smallint");

                    b.Property<string>("AboutProjectTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AboutTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AboutUpperTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactContentDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactContentTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactFormTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactUpperTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HeroButtonTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HeroButtonUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HeroClient")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("HeroClientPercent")
                        .HasColumnType("real");

                    b.Property<string>("HeroDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HeroExperienceListTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("HeroExperienceListYear")
                        .HasColumnType("date");

                    b.Property<string>("HeroImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short?>("HeroProjectCount")
                        .HasColumnType("smallint");

                    b.Property<string>("HeroProjectTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HeroTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HeroVideoButtonTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HeroVideoButtonUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PortfolioContactContactButtonTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PortfolioContactDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PortfolioContactPortfolioButtonTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PortfolioContactTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PortfolioDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PortfolioTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PortfolioUpperTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExperienceDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExperienceTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExperienceUpperTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExperienceListDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExperienceListTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExperienceListUpperTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WhatIKnowDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WhatIKnowTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WhatIKnowUpperTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EducationDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EducationTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TechnologiesDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EducationImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TechnologiesTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TechnologiesUpperTitle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("HomePages");
                });

            modelBuilder.Entity("KJ.Portfolio.Web.Ui.Models.Entities.PortfolioCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PortfolioCategories");
                });

            modelBuilder.Entity("KJ.Portfolio.WebUI.Models.Entities.PortfolioItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Client")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("ProjectYear")
                        .HasColumnType("date");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("PortfolioItems");
                });

            modelBuilder.Entity("KJ.Portfolio.WebUI.Models.Entities.PortfolioTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PortfolioTags");
                });

            modelBuilder.Entity("KJ.Portfolio.WebUI.Models.Entities.Experience", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("HomePageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SocialIconClass1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SocialIconClass2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SocialIconClass3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SocialUrl1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SocialUrl2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SocialUrl3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HomePageId");

                    b.ToTable("Experiences");
                });

            modelBuilder.Entity("KJ.Portfolio.WebUI.Models.Entities.ExperienceListItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("HomePageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HomePageId");

                    b.ToTable("ExperienceListItems");
                });

            modelBuilder.Entity("KJ.Portfolio.WebUI.Models.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("KJ.Portfolio.WebUI.Models.Entities.WhatIKnowCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("HomePageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IconClass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HomePageId");

                    b.ToTable("WhatIKnowCards");
                });

            modelBuilder.Entity("KJ.Portfolio.WebUI.Models.Entities.TechnologiesCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("HomePageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IconClass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HomePageId");

                    b.ToTable("TechnologiesCards");
                });

            modelBuilder.Entity("PortfolioItemPortfolioTag", b =>
                {
                    b.Property<Guid>("ItemsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TagsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ItemsId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("PortfolioItemPortfolioTag");
                });

            modelBuilder.Entity("KJ.Portfolio.WebUI.Models.Entities.PortfolioItem", b =>
                {
                    b.HasOne("KJ.Portfolio.Web.Ui.Models.Entities.PortfolioCategory", "Category")
                        .WithMany("Items")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("KJ.Portfolio.WebUI.Models.Entities.Experience", b =>
                {
                    b.HasOne("KJ.Portfolio.Web.Ui.Models.Entities.HomePage", "HomePage")
                        .WithMany("Experiences")
                        .HasForeignKey("HomePageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HomePage");
                });

            modelBuilder.Entity("KJ.Portfolio.WebUI.Models.Entities.ExperienceListItem", b =>
                {
                    b.HasOne("KJ.Portfolio.Web.Ui.Models.Entities.HomePage", "HomePage")
                        .WithMany("ExperienceListItems")
                        .HasForeignKey("HomePageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HomePage");
                });

            modelBuilder.Entity("KJ.Portfolio.WebUI.Models.Entities.WhatIKnowCard", b =>
                {
                    b.HasOne("KJ.Portfolio.Web.Ui.Models.Entities.HomePage", "HomePage")
                        .WithMany("WhatIKnowCards")
                        .HasForeignKey("HomePageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HomePage");
                });

            modelBuilder.Entity("KJ.Portfolio.WebUI.Models.Entities.TechnologiesCard", b =>
                {
                    b.HasOne("KJ.Portfolio.Web.Ui.Models.Entities.HomePage", "HomePage")
                        .WithMany("TechnologiesCards")
                        .HasForeignKey("HomePageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HomePage");
                });

            modelBuilder.Entity("PortfolioItemPortfolioTag", b =>
                {
                    b.HasOne("KJ.Portfolio.WebUI.Models.Entities.PortfolioItem", null)
                        .WithMany()
                        .HasForeignKey("ItemsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KJ.Portfolio.WebUI.Models.Entities.PortfolioTag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KJ.Portfolio.Web.Ui.Models.Entities.HomePage", b =>
                {
                    b.Navigation("Experiences");

                    b.Navigation("ExperienceListItems");

                    b.Navigation("WhatIKnowCards");

                    b.Navigation("TechnologiesCards");
                });

            modelBuilder.Entity("KJ.Portfolio.Web.Ui.Models.Entities.PortfolioCategory", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
